name: Create Unix toolchain

on:
  push:
    paths:
      - toolchains/unix/build_toolchain.sh

  # Allow developers to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build and deploy toolchain for Unix systems
    runs-on: ubuntu-22.04

    steps:
      - name: Install toolchain build dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: build-essential ninja-build clang llvm re2c
          version: 1.0

      - name: Clone repository
        uses: actions/checkout@v3

      - name: Build toolchain
        run: >
          sh ${GITHUB_WORKSPACE}/toolchains/unix/build_toolchain.sh
             --staging-dir=staging
             --target-dir=target
             --use-lto
             --verbose
